// Generated by CoffeeScript 2.5.1
// import {globals} from './globals.js'

// export class Control
// 	constructor : (@x,@y,@w,@h,@text='',@bg='black',@fg='white') ->
// 		@visible = true
// 		@disabled = false
// 		@textSize = 2
// 	draw : -> console.log 'Control.draw must be overriden!'
// 	inside : (x,y) ->
// 		w = @w * [height/width,width/height][1-globals.TOGGLE]
// 		-w/2 <= x-@x <= w/2 and -@h/2 <= y-@y <= @h/2

// export class CDead extends Control
// 	constructor : (x,y,text,fg='white') ->
// 		super x,y,0,0,text,'black',fg
// 	draw : ->
// 		push()
// 		textSize 2
// 		fill 'black'
// 		text @text,@x,@y
// 		pop()

// export class CRounded extends Control
// 	constructor : (x,y,w,h,text='', @clicker=null) ->
// 		super x,y,w,h,text,'black','white'
// 	draw : ->
// 		if @visible
// 			push()
// 			fill if @disabled then "gray" else 'black'
// 			rect @x,@y,@w,@h,@h/10
// 			textSize @textSize
// 			fill if @disabled then "black" else 'white'
// 			text @text,@x,@y
// 			pop()
// 	click : => if @clicker then @clicker()


//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY29udHJvbHMuanMiLCJzb3VyY2VSb290IjoiLi4iLCJzb3VyY2VzIjpbImNvZmZlZVxcY29udHJvbHMuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFrQ3lDIiwic291cmNlc0NvbnRlbnQiOlsiIyBpbXBvcnQge2dsb2JhbHN9IGZyb20gJy4vZ2xvYmFscy5qcydcclxuXHJcbiMgZXhwb3J0IGNsYXNzIENvbnRyb2xcclxuIyBcdGNvbnN0cnVjdG9yIDogKEB4LEB5LEB3LEBoLEB0ZXh0PScnLEBiZz0nYmxhY2snLEBmZz0nd2hpdGUnKSAtPlxyXG4jIFx0XHRAdmlzaWJsZSA9IHRydWVcclxuIyBcdFx0QGRpc2FibGVkID0gZmFsc2VcclxuIyBcdFx0QHRleHRTaXplID0gMlxyXG4jIFx0ZHJhdyA6IC0+IGNvbnNvbGUubG9nICdDb250cm9sLmRyYXcgbXVzdCBiZSBvdmVycmlkZW4hJ1xyXG4jIFx0aW5zaWRlIDogKHgseSkgLT5cclxuIyBcdFx0dyA9IEB3ICogW2hlaWdodC93aWR0aCx3aWR0aC9oZWlnaHRdWzEtZ2xvYmFscy5UT0dHTEVdXHJcbiMgXHRcdC13LzIgPD0geC1AeCA8PSB3LzIgYW5kIC1AaC8yIDw9IHktQHkgPD0gQGgvMlxyXG5cclxuIyBleHBvcnQgY2xhc3MgQ0RlYWQgZXh0ZW5kcyBDb250cm9sXHJcbiMgXHRjb25zdHJ1Y3RvciA6ICh4LHksdGV4dCxmZz0nd2hpdGUnKSAtPlxyXG4jIFx0XHRzdXBlciB4LHksMCwwLHRleHQsJ2JsYWNrJyxmZ1xyXG4jIFx0ZHJhdyA6IC0+XHJcbiMgXHRcdHB1c2goKVxyXG4jIFx0XHR0ZXh0U2l6ZSAyXHJcbiMgXHRcdGZpbGwgJ2JsYWNrJ1xyXG4jIFx0XHR0ZXh0IEB0ZXh0LEB4LEB5XHJcbiMgXHRcdHBvcCgpXHJcblxyXG4jIGV4cG9ydCBjbGFzcyBDUm91bmRlZCBleHRlbmRzIENvbnRyb2xcclxuIyBcdGNvbnN0cnVjdG9yIDogKHgseSx3LGgsdGV4dD0nJywgQGNsaWNrZXI9bnVsbCkgLT5cclxuIyBcdFx0c3VwZXIgeCx5LHcsaCx0ZXh0LCdibGFjaycsJ3doaXRlJ1xyXG4jIFx0ZHJhdyA6IC0+XHJcbiMgXHRcdGlmIEB2aXNpYmxlXHJcbiMgXHRcdFx0cHVzaCgpXHJcbiMgXHRcdFx0ZmlsbCBpZiBAZGlzYWJsZWQgdGhlbiBcImdyYXlcIiBlbHNlICdibGFjaydcclxuIyBcdFx0XHRyZWN0IEB4LEB5LEB3LEBoLEBoLzEwXHJcbiMgXHRcdFx0dGV4dFNpemUgQHRleHRTaXplXHJcbiMgXHRcdFx0ZmlsbCBpZiBAZGlzYWJsZWQgdGhlbiBcImJsYWNrXCIgZWxzZSAnd2hpdGUnXHJcbiMgXHRcdFx0dGV4dCBAdGV4dCxAeCxAeVxyXG4jIFx0XHRcdHBvcCgpXHJcbiMgXHRjbGljayA6ID0+IGlmIEBjbGlja2VyIHRoZW4gQGNsaWNrZXIoKVxyXG4iXX0=
//# sourceURL=c:\github\2022-008-Berger\coffee\controls.coffee