// Generated by CoffeeScript 2.5.1
import {
  SF
} from './SF.js';

export var SG = class SG extends SF { // Berger Bord
  constructor(name) {
    super(name);
    this.halfTable = false;
  }

};

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU0cuanMiLCJzb3VyY2VSb290IjoiLi4iLCJzb3VyY2VzIjpbImNvZmZlZVxcU0cuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQSxPQUFBO0VBQVEsRUFBUjtDQUFBLE1BQUE7O0FBRUEsT0FBQSxJQUFhLEtBQU4sTUFBQSxHQUFBLFFBQWlCLEdBQWpCLENBQUE7RUFFTixXQUFjLENBQUMsSUFBRCxDQUFBO1NBQ2IsQ0FBTSxJQUFOO0lBQ0EsSUFBQyxDQUFBLFNBQUQsR0FBYTtFQUZBOztBQUZSIiwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0IHtTRn0gZnJvbSAnLi9TRi5qcydcclxuXHJcbmV4cG9ydCBjbGFzcyBTRyBleHRlbmRzIFNGICMgQmVyZ2VyIEJvcmRcclxuXHJcblx0Y29uc3RydWN0b3IgOiAobmFtZSkgLT5cclxuXHRcdHN1cGVyIG5hbWVcclxuXHRcdEBoYWxmVGFibGUgPSBmYWxzZVxyXG4iXX0=
//# sourceURL=c:\github\2022-008-Berger\coffee\SG.coffee