// Generated by CoffeeScript 2.5.1
import {
  SF
} from './SF.js';

export var SH = class SH extends SF { // Berger Bord SVG
  constructor(name) {
    super(name);
    this.halfTable = false;
  }

  drawControls() {}

  draw() {}

};

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU0guanMiLCJzb3VyY2VSb290IjoiLi4iLCJzb3VyY2VzIjpbImNvZmZlZVxcU0guY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQSxPQUFBO0VBQVEsRUFBUjtDQUFBLE1BQUE7O0FBRUEsT0FBQSxJQUFhLEtBQU4sTUFBQSxHQUFBLFFBQWlCLEdBQWpCLENBQUE7RUFFTixXQUFjLENBQUMsSUFBRCxDQUFBO1NBQ2IsQ0FBTSxJQUFOO0lBQ0EsSUFBQyxDQUFBLFNBQUQsR0FBYTtFQUZBOztFQUlkLFlBQWUsQ0FBQSxDQUFBLEVBQUE7O0VBRWYsSUFBTyxDQUFBLENBQUEsRUFBQTs7QUFSRCIsInNvdXJjZXNDb250ZW50IjpbImltcG9ydCB7U0Z9IGZyb20gJy4vU0YuanMnXHJcblxyXG5leHBvcnQgY2xhc3MgU0ggZXh0ZW5kcyBTRiAjIEJlcmdlciBCb3JkIFNWR1xyXG5cclxuXHRjb25zdHJ1Y3RvciA6IChuYW1lKSAtPlxyXG5cdFx0c3VwZXIgbmFtZVxyXG5cdFx0QGhhbGZUYWJsZSA9IGZhbHNlXHJcblxyXG5cdGRyYXdDb250cm9scyA6IC0+XHJcblxyXG5cdGRyYXcgOiAtPlxyXG4iXX0=
//# sourceURL=c:\github\2022-008-Berger\coffee\SH.coffee